### ISSUE TITLE
rewireとjsdomとjest

### ISSUE THREAD

**Issue by kenkenfuttar** [kenkenfuttar/tskmng#6]
index.test.jsでエラー対応策検討中

    TypeError: document.body.innerHTML.$ is not a function

      87 |         let expected = '<input id="inputItem0" name="inputItem" value="' + JSON.stringify(task) + '" type="hidden">';
      88 |         expect(addInput()).toBe();
    > 89 |         let received = document.body.innerHTML.$('#formIndex').html();
         |                                                ^
      90 |         console.log(received);
      91 |         console.log(expected);
      92 |         expect(received).toBe(expected);

      at Object.<anonymous> (test/index.test.js:89:48)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:347:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)

**Comment by kenkenfuttar** [comment]
receivedを抜き出すのではなく、一部を変換して比較することとした。
もともと\quot;と\"での不一致がもとで対処方法を探していた。
